### ISSUE TITLE
SOT-143-4 incorrect pin 1

### ISSUE THREAD

**Issue by zwh2** [Digi-Key/digikey-kicad-library#105]
I noticed the pinout for SP0503BAHTG is incorrect and it stems from the SOT-143-4 footprint being wrong. Here is the datasheet for the part: https://www.littelfuse.com/~/media/files/littelfuse/technical%20resources/documents/data%20sheets/sp05xxba.pdf and one for a generic SOT-143-4: https://www.onsemi.com/pub/Collateral/318A.PDF

**Comment by Reid-L** [comment]
@zwh2 
Thank you for the feedback and correction. Your pull request is for the Main Footprint .pretty which would be overwritten on the next build after it is merged. I added your changes to the src\Source_Footprints\SOT-143-4.kicad_mod so that they will be included in future builds. This was done on Pull Request #110 
Thanks
Reid L
